[ req ]
# Options for the `req` tool (`man req`).
#default_bits        = 2048
#default_keyfile     = private.key
distinguished_name  = req_distinguished_name
string_mask         = utf8only

# SHA-1 is deprecated, so use SHA-2 instead.
default_md          = sha256

# Extension to add when the `req` command is used.
#req_extensions     = server_cert

[ req_distinguished_name ]
# See <https://en.wikipedia.org/wiki/Certificate_signing_request>.
countryName                     = Country Name (2 letter code)
stateOrProvinceName             = State or Province Name
localityName                    = Locality Name
0.organizationName              = Organization Name
organizationalUnitName          = Organizational Unit Name
commonName                      = Common Name
emailAddress                    = Email Address

[ server_cert ]
# Only the subject alt names is left to the client for setting. The rest will
#  be addres by the CA
#subjectAltName = @alt_names

[ alt_names ]
# Multiple DNS can be added
# Limit is 99
# Just increase the trailing number for each DNS name
#DNS.1   =
#DNS.2   =

# Same as above
#IP.1    =
